quotes = [
"Bir so'z bizni hayotning barcha azoblaridan xalos qiladi Bu sevgi",
"Mening tilagim shuki, sizni jinnilik darajasida sevish.",
"O'zingiz bo'lish orqali dunyoni o'zgartiring.",
"Har bir daqiqa yangi boshlanish.",
"Hech qachon sizni tabassum qildira olgan narsadan afsuslanmang.",
"Orzular bilan emas, xotiralar bilan o'ling.",
"Siz tasavvur qila oladigan hamma narsa haqiqatdir.",
"Soddalik - bu eng yuksak nafosat.",
"Baxtli qalb shafqatsiz dunyo uchun eng yaxshi qalqondir.",
"Oq har doim ham yorqin emas va qora har doim ham qorong'i emas.",
"Baxt o'zimizga bog'liq.",
# "Whatever you do, do it well.",
# "What we think, we become.",
# "All limitations are self-imposed.",
# "Tough times never last but tough people do.",
# "Problems are not stop signs, they are guidelines.",
# "Have enough courage to start and enough heart to finish.",
# "I could agree with you but then we’d both be wrong.",
# "Oh, the things you can find, if you don’t stay behind.",
# "Determine your priorities and focus on them.",
# "Be so good they can’t ignore you.",
# "Yesterday you said tomorrow. Just do it.",
# "I don’t need it to be easy, I need it to be worth it.",
# "Never let your emotions overpower your intelligence.",
# "Hech narsa abadiy davom etmaydi, ammo bizda buning xotiralari bor.",
# "Don’t you know your imperfections is a blessing?",
# "Reality is wrong, dreams are for real.",
# "To live will be an awfully big adventure.",
# "Try to be a rainbow in someone’s cloud.",
# "There is no substitute for hard work.",
# "What consumes your mind controls your life.",
# "Strive for greatness.",
# "And still, I rise.",
# "The time is always right to do what is right.",
# "Let the beauty of what you love be what you do.",
# "May your choices reflect your hopes, not your fears.",
# "A happy soul is the best shield for a cruel world.",
# "White is not always light and black is not always dark.",
# "Happiness depends upon ourselves.",
# "Turn your wounds into wisdom.",
# "Change the game, don’t let the game change you.",
# "It hurt because it mattered.",
# "I will remember and recover, not forgive and forget.",
# "The meaning of life is to give life meaning.",
# "When words fail, music speaks.",
# "Embrace the glorious mess that you are.",
# "I have nothing to lose but something to gain.",
# "U o'qiyotganda, men siz uxlayotganingizni sevib qoldim: asta-sekin, keyin birdaniga.",
# "Kecha sizni sevdim, hali ham sevaman, har doim bo'ladi, har doim bo'ladi." ,
# "Men sizning mukammal ekanligingizni ko'rdim va shuning uchun sizni sevdim. Shunda men komil emasligingni ko‘rdim va seni yanada sevib qoldim",
# "Men seni nafaqat borliging uchun, balki sen bilan birga bo'lganim uchun ham sevaman. Men seni nafaqat o'zingdan qilganing uchun, balki mendan qilgan narsang uchun ham sevaman. Men seni o'zimning o'zimdan olib chiqqan qismim uchun yaxshi ko'raman." ,
# "Haqiqiy oshiq - bu peshonangizdan o'pish yoki ko'zlaringizga tabassum qilish yoki shunchaki kosmosga tikilish orqali sizni hayajonga soladigan odam.",
# "Butun dunyoda men uchun siznikidek yurak yo'q. Butun dunyoda senga mendek muhabbat yo‘q",
"Men sizni har doim haqiqiy sevgi bilan sevaman unitolmayman",
"Siz haqingizda o'ylash meni hushyorlikka olib keladi. ",
"Siz bilan bo'lish meni tirik qoldiradi.",
"Sizni orzu qilish meni uyquga olib keladi.",
"Menga u '4' yurak urishi kerak bo'lganidek kerak." ,
"Meni tanla, tanla, sev.",
]

emojis = [
"💯", "🔅", "💬", "💭", "🗯", "🌻",
"⚡️", "💫", "🌟", "🍃","👉","✍️","🫶"
]

morse_dict = {
'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....',
'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.',
'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
'Y': '-.--', 'Z': '--..', '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-',
'5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.', " " : ':'
}
